/* DO NOT EDIT THIS FILE - it is machine generated */

#include <jni.h>

#ifndef __sample__
#define __sample__

#ifdef __cplusplus
extern "C"
{
#endif


#ifdef __cplusplus
}
#endif

#endif /* __sample__ */
